# Generated by Django 3.0.3 on 2020-03-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120)),
                ('brand_id', models.IntegerField()),
                ('brand_cat_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=120)),
                ('cat_id', models.IntegerField()),
                ('cat_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_id', models.IntegerField()),
                ('slug', models.SlugField()),
                ('product_subcat_id', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image1', models.ImageField(blank=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_name', models.CharField(max_length=120)),
                ('subcat_id', models.IntegerField()),
                ('subcat_description', models.CharField(max_length=300)),
            ],
        ),
    ]
