# Generated by Django 3.0.3 on 2020-03-08 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_name', models.CharField(max_length=120)),
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_description', models.CharField(max_length=400)),
                ('cat_image', models.ImageField(default='default.jpg', upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_id', models.IntegerField()),
                ('product_subcat_id', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('image1', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcat_name', models.CharField(max_length=120)),
                ('subcat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subcat_description', models.CharField(max_length=300)),
                ('subcat_image', models.ImageField(upload_to='gallery')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopping.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('brand', models.IntegerField(primary_key=True, serialize=False)),
                ('subcat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopping.SubCategory')),
            ],
        ),
    ]
