# Generated by Django 3.0.3 on 2020-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0002_auto_20200304_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
