# Generated by Django 3.0.4 on 2020-03-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0002_auto_20200318_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
