# Generated by Django 3.0.3 on 2020-03-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0003_auto_20200308_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subcat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopping.Brand'),
        ),
    ]
