# Generated by Django 3.0.4 on 2020-03-14 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='DOB',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
