# Generated by Django 3.0.3 on 2020-03-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0004_auto_20200308_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_subcat_id',
            new_name='product_brand',
        ),
    ]
