# Generated by Django 3.0.4 on 2020-03-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0006_auto_20200320_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='DOB',
        ),
    ]
