# Generated by Django 3.0.3 on 2020-03-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
