# Generated by Django 3.0.4 on 2020-03-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0008_auto_20200320_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address2',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
