# Generated by Django 3.0.4 on 2020-03-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopping', '0009_auto_20200320_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
