"""
Django settings for onlineshopping project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nc7i*j)(zvxy1c4i+fewbfvx2p0rzcw-^s1p10a14m7wk0mkif'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD:onlineshopping/onlineshopping/settings.py
<<<<<<< HEAD:onlineshopping/onlineshopping/onlineshopping/settings.py
   'myshopping',
<<<<<<< HEAD:onlineshopping/onlineshopping/onlineshopping/settings.py
=======
=======
>>>>>>> LoginandSignupStyling:onlineshopping/onlineshopping/onlineshopping/settings.py
    'django.contrib.sites',

    'myshopping',
<<<<<<< HEAD
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
<<<<<<< HEAD:onlineshopping/onlineshopping/settings.py
<<<<<<< HEAD
>>>>>>> TestBranch1:onlineshopping/onlineshopping/settings.py
=======
   'crispy_forms',
   'bootstrap4',
    'bootstrapform',
   
>>>>>>> TestBranch4:onlineshopping/onlineshopping/settings.py
=======
    'cart',
>>>>>>> TestBranch3
=======
    'bootstrap4',
    'crispy_forms',
=======
]
>>>>>>> LoginandSignupStyling:onlineshopping/onlineshopping/onlineshopping/settings.py

>>>>>>> TestBranch1
]
CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'onlineshopping.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates', 'allauth')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',

            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

)

WSGI_APPLICATION = 'onlineshopping.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
<<<<<<< HEAD:onlineshopping/onlineshopping/settings.py
<<<<<<< HEAD
<<<<<<< HEAD:onlineshopping/onlineshopping/onlineshopping/settings.py
        'NAME': 'pTest',
        'USER':'root',
        'PASSWORD':'',
        'HOST':'localhost'
=======
=======
>>>>>>> LoginandSignupStyling:onlineshopping/onlineshopping/onlineshopping/settings.py
        'NAME': 'onlineshop',
        'USER': 'root',
        'PASSWORD': 'omaramora11',
        'HOST': 'localhost'
<<<<<<< HEAD:onlineshopping/onlineshopping/settings.py
>>>>>>> TestBranch1:onlineshopping/onlineshopping/settings.py
=======
        'NAME': 'onlineShopping',
        'USER': 'lamis',
        'PASSWORD': '1234',
        'HOST': 'localhost',
>>>>>>> TestBranch3
=======
>>>>>>> LoginandSignupStyling:onlineshopping/onlineshopping/onlineshopping/settings.py
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
<<<<<<< HEAD
<<<<<<< HEAD:onlineshopping/onlineshopping/onlineshopping/settings.py

SITE_ID = 1
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = "/media/"
LOGIN_REDIRECT_URL = '/'
<<<<<<< HEAD
=======
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
>>>>>>> TestBranch4:onlineshopping/onlineshopping/settings.py
=======
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://example.com/media/", "http://media.example.com/"
MEDIA_URL = '/media/'
>>>>>>> TestBranch3
=======
CRISPY_TEMPLATE_PACK = 'bootstrap4'
>>>>>>> TestBranch1
