<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-03-09 18:08

=======
# Generated by Django 3.0.3 on 2020-03-16 02:43

from django.conf import settings
>>>>>>> TestBranch3
=======
# Generated by Django 3.0.3 on 2020-03-17 18:01

from django.conf import settings
>>>>>>> TestBranch4
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
        ('myshopping', '0005_auto_20200308_0556'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myshopping', '0001_initial'),
>>>>>>> TestBranch3
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myshopping', '0008_userprofile'),
>>>>>>> TestBranch4
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
            name='OrderItem',
=======
            name='Cart',
>>>>>>> TestBranch4
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('purchased', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopping.Product')),
<<<<<<< HEAD
=======
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopping.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> TestBranch3
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> TestBranch4
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
<<<<<<< HEAD
                ('ref_code', models.CharField(max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_orderd', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='cart.OrderItem')),
=======
=======
>>>>>>> TestBranch4
                ('ordered', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('orderitems', models.ManyToManyField(to='cart.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
<<<<<<< HEAD
>>>>>>> TestBranch3
=======
>>>>>>> TestBranch4
            ],
        ),
    ]
